services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile 
    volumes: 
      - laravel-storage-production:/var/www/storage:ro
      - laravel-public-assets:/var/www/public/build:ro
    networks:
      - traefik-network     # Public-facing network (Traefik)
      - app-network         # Private app network (connects to php-fpm)
    ports:
      - "${NGINX_PORT:-8089}:80"
    depends_on:
      - php-fpm  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lara-job.rule=Host(`jobs.gkibria121.com`)"
      - "traefik.http.routers.lara-job.entrypoints=web"
      - "traefik.http.services.lara-job.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-network"
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production 
    volumes:
      - laravel-public-assets:/var/www/public/build
      - laravel-storage-production:/var/www/storage 
    env_file:
      - .env
    networks:
      - app-network          # Internal network (php-fpm <-> db/redis)
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    user: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-app}
      - POSTGRES_USER=${POSTGRES_USERNAME:-laravel}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-laravel} -d ${POSTGRES_DATABASE:-app}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine 
    networks:
      - app-network 

networks:
  traefik-network:
    external: true   # Traefik network (already defined globally)
  app-network:
    driver: bridge   # Internal network for php-fpm, postgres, redis

volumes:
  postgres-data-production:
  laravel-storage-production:
  laravel-public-assets:
