services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile 
    volumes: 
      # -----------------------------------------------------------
      - laravel-storage-production:/var/www/storage:ro
      - laravel-public-assets:/var/www/public/build:ro
    networks:
      - laravel-production
    ports: 
      # -----------------------------------------------------------
      - "${NGINX_PORT:-8089}:80"
    depends_on:
     - php-fpm 

  php-fpm:
    # For the php-fpm service, we will create a custom image to install the necessary PHP extensions and setup proper permissions.
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production 
    volumes:
      - laravel-public-assets:/var/www/public/build  # Mount built public assets to ensure the manifest.json and hashed files match between Nginx and PHP-FPM
      - laravel-storage-production:/var/www/storage  # Mount the storage volume
    env_file:
      - .env
    networks:
      - laravel-production  
    depends_on:
    -  postgres

  postgres:
    image: postgres:16
    restart: unless-stopped
    user: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-app}
      - POSTGRES_USER=${POSTGRES_USERNAME:-laravel}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    networks:
      - laravel-production 

  redis:
    image: redis:alpine 
    networks:
      - laravel-production 
 

networks:
  # Attach the service to the 'laravel' network.
  # -----------------------------------------------------------
  # This custom network allows all services within it to communicate using their service names as hostnames.
  # For example, 'php-fpm' can connect to 'postgres' by using 'postgres' as the hostname.
  # -----------------------------------------------------------
  laravel-production:

volumes:
  postgres-data-production:
  laravel-storage-production:
  laravel-public-assets:
